#!/usr/bin/env python3
"""payload.py — audit reference payload size per skill.

Computes how many bytes each skill injects into adapter prompts when
`inject_references` and/or `inject_fewshot` are enabled. Output is the
baseline used to decide which references need compression in Phase 2.

Usage:
    orquestrum audit payload
    orquestrum audit payload --threshold-kb 30
    orquestrum audit payload --output docs/baselines/payload-audit-2026-05.md
"""
import argparse
import sys
from pathlib import Path

from orquestrum.lib.frontmatter import parse_skill
from orquestrum.lib.paths import canonical_assets_root
from orquestrum.lib.rewrite import extract_inject_blocks

# Audit is read-only against canonical SDD content; works in dev and wheel
# modes alike. The --output flag is user-controlled.
ROOT       = canonical_assets_root()
SKILLS_DIR = ROOT / 'skills'


def _ref_file(skill_dir: Path, suffix: str) -> Path | None:
    refs = skill_dir / 'references'
    if not refs.is_dir():
        return None
    candidates = list(refs.glob(f'*-{suffix}.md'))
    if suffix == 'references' and not candidates:
        candidates = list(refs.glob('*-index.md'))
    return candidates[0] if candidates else None


def _payload_bytes(file: Path | None, mode: str) -> int:
    if not file:
        return 0
    raw = file.read_text(encoding='utf-8')
    if mode == 'compact':
        extracted = extract_inject_blocks(raw)
        # If no inject markers, compact mode falls back to full content
        return len(extracted.encode('utf-8')) if extracted else len(raw.encode('utf-8'))
    return len(raw.encode('utf-8'))


def audit() -> list[dict]:
    rows: list[dict] = []
    for skill_dir in sorted(SKILLS_DIR.iterdir()):
        skill_file = skill_dir / 'SKILL.md'
        if not skill_file.exists():
            continue
        skill = parse_skill(skill_file)

        ref_file = _ref_file(skill_dir, 'references')
        fs_file  = _ref_file(skill_dir, 'fewshot')

        ref_mode = skill.inject_refs if skill.inject_refs != 'false' else None
        fs_mode  = skill.inject_fewshot if skill.inject_fewshot != 'false' else None

        ref_bytes = _payload_bytes(ref_file, ref_mode) if ref_mode else 0
        fs_bytes  = _payload_bytes(fs_file, fs_mode)   if fs_mode  else 0

        rows.append({
            'skill':     skill_dir.name,
            'ref_mode':  ref_mode or '-',
            'ref_bytes': ref_bytes,
            'fs_mode':   fs_mode or '-',
            'fs_bytes':  fs_bytes,
            'total':     ref_bytes + fs_bytes,
        })
    rows.sort(key=lambda r: r['total'], reverse=True)
    return rows


def render_markdown(rows: list[dict], threshold_bytes: int) -> str:
    total = sum(r['total'] for r in rows)
    over  = sum(1 for r in rows if r['total'] > threshold_bytes)
    lines = [
        '# Reference Payload Audit',
        '',
        f'Threshold for Phase 2 compression: **{threshold_bytes // 1024} KB**.',
        f'Total injected bytes across all skills: **{total:,} B** ({total // 1024} KB).',
        f'Skills exceeding threshold: **{over}**.',
        '',
        '| # | Skill | Ref mode | Ref bytes | Fewshot mode | Fewshot bytes | Total | Compress? |',
        '|---|-------|----------|----------:|--------------|--------------:|------:|:---------:|',
    ]
    for i, r in enumerate(rows, 1):
        flag = '⚠️ YES' if r['total'] > threshold_bytes else ''
        lines.append(
            f'| {i} | `{r["skill"]}` | {r["ref_mode"]} | {r["ref_bytes"]:,} | '
            f'{r["fs_mode"]} | {r["fs_bytes"]:,} | {r["total"]:,} | {flag} |'
        )
    lines += [
        '',
        '> Generated by `orquestrum audit payload`. Re-run after every change to '
        'skill references to detect drift. Anything > threshold is a candidate '
        'for `inject_references: compact` or for the static-compression pipeline '
        '(`orquestrum compact`, Phase 2).',
        '',
    ]
    return '\n'.join(lines)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        prog='orquestrum audit payload',
        description='Audit reference payload size per skill.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            'Examples:\n'
            '  orquestrum audit payload\n'
            '  orquestrum audit payload --threshold-kb 50\n'
            '  orquestrum audit payload --output docs/baselines/payload.md'
        ),
    )
    parser.add_argument('--threshold-kb', type=int, default=30,
                        help='Threshold in KB above which a skill is flagged for compression (default 30)')
    parser.add_argument('--output', metavar='PATH',
                        help='Write markdown report to this path (also prints to stdout)')
    args = parser.parse_args(argv)

    threshold_bytes = args.threshold_kb * 1024
    rows = audit()
    md = render_markdown(rows, threshold_bytes)
    print(md)

    if args.output:
        out = Path(args.output).resolve()
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(md, encoding='utf-8')
        print(f'\nWritten: {out}', file=sys.stderr)


if __name__ == '__main__':
    main()
